<template>
    <div class="loading-box row align-items-center">
        <div>
            <div class="loadingio-spinner-spinner-tx3plccp2hp">
                <div class="ldio-kxd1o6u922">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
            <div>{{text}}</div>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        text: {
            required: false,
            type: String,
            default: 'Please wait...',
        }
    }
}
</script>

<style lang="scss" scoped>
@import "../style";

.loading-box {
    position: fixed;
    top: 0;
    width: 100%;
    height: 100vh;
    margin: auto;
    background: rgba($clr-1, 0.7);
    box-shadow: 0 0 9px $clr-1;
    z-index: 1199;
    left: 0;
    right: 0;
    text-align: center;
}
@keyframes ldio-kxd1o6u922 {
    0% {
        opacity: 1
    }
    100% {
        opacity: 0
    }
}

.ldio-kxd1o6u922 div {
    left: 94px;
    top: 48px;
    position: absolute;
    animation: ldio-kxd1o6u922 linear 1s infinite;
    background: $clr-2;
    width: 12px;
    height: 24px;
    border-radius: 6px / 12px;
    transform-origin: 6px 52px;
}

.ldio-kxd1o6u922 div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -0.9166666666666666s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(2) {
    transform: rotate(30deg);
    animation-delay: -0.8333333333333334s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(3) {
    transform: rotate(60deg);
    animation-delay: -0.75s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(4) {
    transform: rotate(90deg);
    animation-delay: -0.6666666666666666s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(5) {
    transform: rotate(120deg);
    animation-delay: -0.5833333333333334s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(6) {
    transform: rotate(150deg);
    animation-delay: -0.5s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(7) {
    transform: rotate(180deg);
    animation-delay: -0.4166666666666667s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(8) {
    transform: rotate(210deg);
    animation-delay: -0.3333333333333333s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(9) {
    transform: rotate(240deg);
    animation-delay: -0.25s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(10) {
    transform: rotate(270deg);
    animation-delay: -0.16666666666666666s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(11) {
    transform: rotate(300deg);
    animation-delay: -0.08333333333333333s;
    background: $clr-2;
}

.ldio-kxd1o6u922 div:nth-child(12) {
    transform: rotate(330deg);
    animation-delay: 0s;
    background: $clr-2;
}

.loadingio-spinner-spinner-tx3plccp2hp {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    //background: #ffffff;
}

.ldio-kxd1o6u922 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}

.ldio-kxd1o6u922 div {
    box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>
